const angular = require('angular');
require('angular-mocks');
require('./resource_getall_test.js');
require('./resource_create_test.js');
require('./resource_update_test.js');
require('./resource_remove_test.js');
require('../../app/js/entry.js');
require('./user_controller_test.js');
require('./auth_controller_test.js');
require('./signup_controller_test.js');
require('./signin_controller_test.js');
require('./resync_controller_test.js');
require('./fb_user_auth_test');
